### ISSUE TITLE
Notification when some one joins your event

### ISSUE THREAD

**Issue by mubashariqbal** [madglory/nowplayus#80]
We need to come up with an optional way (@tweet or DM perhaps) that a user can configure per event to get notified when someone joins their event

**Comment by erkattak** [comment]
I think it should be a DM.  We'd either respect their notification wishes via the checkbox we already have or add another option. 

This brings up another thing I've been thinking about which is queuing. If we start doing this "on join" we should queue tweets and let a worker go thru them. That way if we do hit the rate limit, we can re-queue the job for a later time

**Comment by blainsmith** [comment]
DMs would cause issues if people are not followers of each other on Twitter. Right now anyone can join a game I have scheduled, but I would have to be following those players to get a DM from them.

**Comment by erkattak** [comment]
After talking with @mubashariqbal we think that adding a checkbox on the Event to be notified via DM is the way to go. It'd work something like this:

Listener for Event creation where notify_host_via_direct_message is true
  if host doesn't follow nowplayus, auto follow on their behalf
  *\* ensure this is worded properly on the event form **

Listener for participant where event.notify_host_via_direct_message is true
  unless participant has previously joined event, notify host (to avoid multiple DMs due to someone leave/joining more than once)

Create deleted_at column on Participant table and add "acts_as_paranoid" to the model, so we can track if someone previously joined the event. 

``` ruby
Participant.find_by_event_id_and_user_id(event.id, user.id).with_deleted.count
```

Any other thoughts on this?

**Comment by mubashariqbal** [comment]
If we're worried about hitting Twitter limits and such, we can do ask everyone for their email address, so we could send the notification via email instead.

**Comment by sethlouey** [comment]
What is less annoying but more practical for user experience? I get too many emails as is.

**Comment by erkattak** [comment]
Letting them choose one or the other would be fine.

SendGrid has a free tier plan on Heroku, too.

**Comment by erkattak** [comment]
I'm hesitant to add this functionality until we get some sort of queuing happening. I don't think doing this on Heroku would be free (we'd probably have to pay for some redis plugin or at least a worker).

**Comment by erkattak** [comment]
Started doing this on a local branch until we figure out how we want to handle it in production.

Added the @nowplayus oauth_token and secret to the Heroku environment

**Comment by erkattak** [comment]
We can add https://addons.heroku.com/redistogo for free, but it's not persistent - which is fine I think because we won't have that many jobs and who cares if it happens to not notify a few people if it were to reset.

We can use resque or sidekiq - I lean toward sidekiq
